use std::{
    fs::{self, OpenOptions},
    io::{self, ErrorKind, Write},
    path::Path,
};

use convert_case::{Case, Casing};
use jiff::Timestamp;

use crate::{cli::MigrationArgs, commands::CommandResult, project::Project};

pub(crate) fn run(args: MigrationArgs) -> CommandResult {
    let project = Project::discover()?;
    let migrations = project.migrations_dir();

    fs::create_dir_all(&migrations)?;

    let name = normalize_name(&args.name)?;

    let version = Timestamp::now().strftime("%Y%m%d%H%M%S").to_string();

    if args.simple {
        create_simple(&migrations, &version, &name)?;
    } else {
        create_reversible(&migrations, &version, &name)?;
    }

    Ok(())
}

fn create_simple(migrations: &Path, version: &str, name: &str) -> io::Result<()> {
    let path = migrations.join(format!("{version}_{name}.sql"));

    let contents = format!(
        "\
-- Migration: {name}
-- Generated by Rusty CLI
-- Type: simple

-- Write migration SQL here.
"
    );

    write_new(&path, &contents)?;

    println!("Created migration:");
    println!("  {}", path.display());

    Ok(())
}

fn create_reversible(migrations: &Path, version: &str, name: &str) -> io::Result<()> {
    let up = migrations.join(format!("{version}_{name}.up.sql"));

    let down = migrations.join(format!("{version}_{name}.down.sql"));

    let up_contents = format!(
        "\
-- Migration: {name}
-- Generated by Rusty CLI
-- Direction: up

-- Write forward migration SQL here.
"
    );

    let down_contents = format!(
        "\
-- Migration: {name}
-- Generated by Rusty CLI
-- Direction: down

-- Write rollback SQL here.
"
    );

    write_new(&up, &up_contents)?;

    if let Err(error) = write_new(&down, &down_contents) {
        let _ = fs::remove_file(&up);
        return Err(error);
    }

    println!("Created reversible migration:");
    println!("  up   {}", up.display());
    println!("  down {}", down.display());

    Ok(())
}

fn write_new(path: &Path, contents: &str) -> io::Result<()> {
    let mut file = OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(path)
        .map_err(|error| {
            if error.kind() == ErrorKind::AlreadyExists {
                io::Error::new(
                    ErrorKind::AlreadyExists,
                    format!(
                        "refusing to overwrite existing migration: {}",
                        path.display()
                    ),
                )
            } else {
                error
            }
        })?;

    file.write_all(contents.as_bytes())
}

fn normalize_name(raw: &str) -> io::Result<String> {
    let converted = raw.to_case(Case::Snake);

    let parts: Vec<&str> = converted
        .split('_')
        .filter(|part| !part.is_empty())
        .collect();

    if parts.is_empty() {
        return Err(io::Error::new(
            ErrorKind::InvalidInput,
            "migration name must contain letters or numbers",
        ));
    }

    let name = parts.join("_");

    if !name.chars().all(|character| {
        character.is_ascii_lowercase() || character.is_ascii_digit() || character == '_'
    }) {
        return Err(io::Error::new(
            ErrorKind::InvalidInput,
            "migration name contains unsupported characters",
        ));
    }

    Ok(name)
}
