FROM rust:1.98.1-bookworm

RUN rustup component add rustfmt clippy \
    && cargo install topcoat-cli \
        --version 0.8.1 \
        --locked \
    && cargo install sqlx-cli \
        --version 0.9.0 \
        --locked \
        --no-default-features \
        --features rustls,postgres

WORKDIR /app

ENV HOST=0.0.0.0 \
    PORT=3000 \
    CARGO_TERM_COLOR=always \
    RUST_BACKTRACE=1

EXPOSE 3000

CMD ["topcoat", "dev"]
