-- Migration: create_contacts
-- Generated by Rusty CLI
-- Direction: up

CREATE TABLE public.contacts (
                                 id UUID PRIMARY KEY,

                                 name TEXT NOT NULL
                                     CHECK (
                                         char_length(btrim(name)) BETWEEN 1 AND 200
                                         ),

                                 email TEXT NOT NULL
                                     CHECK (
                                         char_length(email) BETWEEN 3 AND 320
                                         ),

                                 created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
                                 updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX contacts_email_unique
    ON public.contacts (lower(email));