[package]
name = "rusty-cli"
version = "0.1.0"
edition = "2024"
rust-version = "1.98"

[[bin]]
name = "rusty"
path = "src/main.rs"

[dependencies]
clap = { version = "=4.6.7", features = ["derive"] }
convert_case = "=0.12.0"
jiff = "=0.2.37"
proc-macro2 = { version = "=1.0.107", features = ["span-locations"] }
syn = { version = "=3.0.6", features = ["full", "visit"] }